site_name: GoToSocial Documentation
theme: readthedocs
repo_url: https://github.com/superseriousbusiness/gotosocial
copyright: GoToSocial is licensed under the GNU AGPL v3 LICENSE. Copyright (C) 2021 the GoToSocial Authors.
plugins:
  - render_swagger

extra_javascript:
  - assets/js/swagger-ui-bundle.js

extra_css:
  - assets/css/swagger-ui.css

nav:
  - "Home": "index.md"
  - "Installation Guide":
    - "installation_guide/index.md"
    - "installation_guide/quick_and_dirty.md"
    - "installation_guide/binary.md"
    - "installation_guide/docker.md"
  - "Configuration":
    - "configuration/index.md"
    - "configuration/general.md"
    - "configuration/database.md"
    - "configuration/template.md"
    - "configuration/accounts.md"
    - "configuration/media.md"
    - "configuration/storage.md"
    - "configuration/statuses.md"
    - "configuration/letsencrypt.md"
    - "configuration/oidc.md"
    - "configuration/smtp.md"
  - "Admin":
    - "admin/index.md"
    - "admin/admin_panel.md"
    - "admin/cli.md"
    - "admin/backup_and_restore.md"
  - "User Guide":
    - "user_guide/index.md"
    - "user_guide/posts.md"
    - "user_guide/password_management.md"
  - "Federation":
    - "federation/index.md"
    - "federation/principles.md"
    - "federation/security.md"
    - "Behaviors":
      - "federation/behaviors/outbox.md"
      - "federation/behaviors/conversation_threads.md"