name: gotosocial-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cairosvg==2.7.1
  - mkdocs-material-extensions==1.3.1
  - mkdocs-material==9.5.15
  - mkdocs==1.5.3
  - pillow==10.2.0
  - pip==24
  - python==3.12
  - mkdocs-include-markdown-plugin=6.2.0
  - pip:
    - mkdocs-swagger-ui-tag==0.6.9
